[package]
name = "proot"
version = "0.1.0"
edition = "2024"
description = "Wrapper around gh CLI"

[dependencies]
anyhow = "1.0.83"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
